# Copyright (c) Nebari Development Team.
# Distributed under the terms of the Modified BSD License.

# jovyan@ce568d131ea5:~$ pip freeze | grep -iE "jupyter|ipywidgets"
# jupyter-core==4.11.1
# jupyter-server==1.18.1
# jupyter-telemetry==0.1.0
# jupyter_client==7.3.5
# jupyterhub==3.0.0
# jupyterlab==3.4.6
# jupyterlab-pygments==0.2.2
# jupyterlab_server==2.15.1


name: default
channels:
  - conda-forge
dependencies:
  # general
  - pip

  # jupyterhub/jupyterlab
  - nb_conda_kernels
  - ipython > 7
  - jupyter-server-proxy
  - "jupyter_server>=1.18.1"
  - jupyterlab >=3
  - jupyter_client
  - jupyter_console
  - jupyterhub==3.1.1
  - nbconvert
  - nbval
  - retrolab

  # jupyterlab extensions
  - dask_labextension >= 5.3.0
  - jupyterlab-git >=0.30.0
  - sidecar >=0.5.0
  - jupyter-videochat >=0.5.0
  - ipywidgets ==7.7.1
  - ipyleaflet >=0.13.5
  - pyviz_comms >=2.0.1
  - jupyter-resource-usage >=0.6.0
  - nbgitpuller
  - jupyterlab_code_formatter
  - jupyterlab-spellchecker >= 0.7.3

  # cds dashboards
  # - cdsdashboards-singleuser >=0.6.3
  # - jhsingle-native-proxy >=0.7.6

  # viz tools
  - param
  - python-graphviz
  - plotly >=5.0
  - ipympl
  - bokeh <3.0.0

  # testing, docs, linting
  - pytest
  - hypothesis
  - flake8
  - sphinx
  - pytest-cov
  - black
  - isort
  - importnb

  - pip:
      # vscode jupyterlab launcher
      - git+https://github.com/betatim/vscode-binder
      - jupyterlab-conda-store >=0.2.7
      - jupyter-tensorboard
      - jupyterlab_nvdashboard

# jovyan@ce568d131ea5:~$ pip freeze | grep -iE "jupyter|ipywidgets"
# jupyter-core==4.11.1
# jupyter-server==1.18.1
# jupyter-telemetry==0.1.0
# jupyter_client==7.3.5
# jupyterhub==3.0.0
# jupyterlab==3.4.6
# jupyterlab-pygments==0.2.2
# jupyterlab_server==2.15.1
