# Copyright (c) Nebari Development Team.
# Distributed under the terms of the Modified BSD License.

name: default
channels:
  - conda-forge
dependencies:
  # general
  - pip

  # jupyterhub/jupyterlab
  - nb_conda_kernels
  - ipython > 7
  - jupyter-server-proxy >=4.1.1
  - "jupyter_server>=2.13.0"
  - jupyterlab >=4
  - jupyter_client
  - jupyter_console
  - nbconvert
  - nbval

  # jupyterhub extension

  # jupyterlab extensions
  - dask_labextension >= 5.3.0
  - jupyterlab-git >=0.30.0
  - sidecar >=0.5.0
  - ipywidgets >= 8.0.0
  - ipyleaflet >=0.13.5
  - pyviz_comms >=2.0.1
  - jupyter-resource-usage >=0.6.0
  - nbgitpuller
  - jupyterlab_code_formatter
  - jupyterlab-spellchecker >= 0.7.3
  - jupyterlab-pioneer
  - jupyter-ai
  - jupyterlab-favorites >=3.2.1
  - jupyter-scheduler >=2.5.2

  # viz tools
  - param
  - python-graphviz
  - plotly >=5.0
  - ipympl
  - bokeh >=3.0

  # testing, docs, linting
  - pytest
  - hypothesis
  - flake8
  - sphinx
  - pytest-cov
  - black
  - isort
  - importnb
  - git-lfs

  - pip:
      # vscode jupyterlab launcher
      - git+https://github.com/betatim/vscode-binder
      - argo-jupyter-scheduler==2024.3.1
      - jhub-apps==2024.4.1
      - jupyterlab-nebari-mode==0.3.0
      - jupyterlab-conda-store==2024.3.1
      - jupyterhub==5.0.0b1
