name: Linter for Dockerfiles
description: Linter for modified docker files

inputs:
  file-path:
    description: Source path to docker image
    required: true
    type: string

outputs:
  status:
    description: Linter status
    value: ${{ steps.filter.outputs.value }}

runs:
  using: composite

  steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        # Detect changes against the most recent commit on the same branch before the push
        base: ${{ github.ref }}
        filters: |
          source:
            - '${{ inputs.file-path }}'

    # Run only if docker files weren't changed
    - name: Terminate if file not updated
      if: steps.filter.outputs.source == 'false'
      run: |
        echo -e "\e[1;32m No changes detected, skipping build \e[0m \u2705"
        exit 0
      shell: bash

    # Run only if docker files were changed
    - name: Lint Dockerfiles
      if: steps.filter.outputs.source == 'true'
      uses: jbergstroem/hadolint-gh-action@v1
      with:
        dockerfile: ${{ inputs.file-path }}
        output_format: tty
        error_level: 0