name: Build environment
description: Build runner environment

inputs:
  python-version:
    description: Python version
    required: false
    default: 3.8
    type: string

runs:
  using: composite
  steps:
    - name: Set Up Python 🐍
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Dev Dependencies 📦
      run: |
        pip install --upgrade pip
        pip install --upgrade -r runner-requirements.txt
      shell: bash