name: base
channels:
  - conda-forge
dependencies:
  - pip==21.1.2
  - jupyterhub==4.0.2
  - jupyterhub-kubespawner==4.2.0
  - oauthenticator==15.1.0
  - escapism==1.0.1
  - python-kubernetes
  - kubernetes_asyncio
  - jupyterhub-idle-culler==1.2.1
  - sqlalchemy==1.4.46
  # JHub Apps dependencies
  - fastapi
  - panel
  - bokeh
  - uvicorn
  - python-multipart
  - pip:
    - nebari-jupyterhub-theme
    - python-keycloak==0.26.1
    - git+https://github.com/nebari-dev/jhub-apps.git@b79f746bf146282bf0a17c650e726542cb8d5a66
    - jupyterlab_pioneer
