name: base
channels:
  - conda-forge
dependencies:
  - pip==21.1.2
  - jupyterhub==3.1.1
  - jupyterhub-kubespawner==4.2.0# ==1.1.0
  - oauthenticator==15.1.0
  - escapism==1.0.1
  - kubernetes_asyncio
  # - cdsdashboards==0.6.3
  - jupyterhub-idle-culler==1.2.1
  - sqlalchemy==1.4.46
  - pip:
        - nebari-jupyterhub-theme
        - python-keycloak==0.26.1

# from Z2JH chart hub image
# > pip freeze | grep -iE 'pip|jupy|oath|escap|cds|sqlalch|keycloak'
# escapism==1.0.1
# jupyter-telemetry==0.1.0
# jupyterhub==3.0.0
# jupyterhub-firstuseauthenticator==1.0.0
# jupyterhub-hmacauthenticator==1.0
# jupyterhub-idle-culler==1.2.1
# jupyterhub-kubespawner==4.2.0
# jupyterhub-ldapauthenticator==1.3.2
# jupyterhub-ltiauthenticator==1.2.0
# jupyterhub-nativeauthenticator==1.1.0
# jupyterhub-tmpauthenticator==0.6
# sqlalchemy-cockroachdb==1.4.3
# SQLAlchemy==1.4.41


# from conda install "jupyterhub=3" in a fresh env on 2023/06/29
# > conda list | grep -E 'pip|jupy|oath|escap|cds|sqlalch|keycloak'
# jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
# jupyterhub                3.1.1              pyh2a2186d_0    conda-forge
# jupyterhub-base           3.1.1              pyh2a2186d_0    conda-forge
# pip                       23.1.2             pyhd8ed1ab_0    conda-forge
# sqlalchemy                2.0.17          py311h459d7ec_0    conda-forge