name: base
channels:
  - conda-forge
dependencies:
  - pip==21.1.2
  - jupyterhub==5.1.0
  - jupyterhub-kubespawner==4.2.0
  - oauthenticator==16.3.0
  - escapism==1.0.1
  - python-kubernetes
  - kubernetes_asyncio==29.0.0
  - jupyterhub-idle-culler==1.2.1
  - sqlalchemy==1.4.46
  - pip:
    - nebari-jupyterhub-theme==2024.7.1
    - python-keycloak==0.26.1
    - git+https://github.com/nebari-dev/jhub-apps.git@cd088bf8f5f0cf89782ce239887aba1b38d807e1
