name: base
channels:
  - conda-forge
dependencies:
  - pip==21.1.2
  - jupyterhub-kubespawner==4.2.0
  - oauthenticator==15.1.0
  - escapism==1.0.1
  - python-kubernetes
  - kubernetes_asyncio
  - jupyterhub-idle-culler==1.2.1
  - sqlalchemy==1.4.46
  - pip:
    - nebari-jupyterhub-theme
    - python-keycloak==0.26.1
    - jhub-apps==2024.1.6
    - jupyterhub@git+https://github.com/jupyterhub/jupyterhub/archive/135be72470b9c414a19c270f458ba2fc7532146a.zip
