# Build and push images to:
# GitHub Container Registry (ghcr.io)
# Red Hat Container Registry (quay.io)
name: "Build Docker Images"

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile.*"
      - "dask-worker/*"
      - "jupyterhub/*"
      - "jupyterlab/*"
      - "scripts/*"
      - ".github/workflows/build-push-docker.yaml"
    tags:
      - "*"

env:
  DOCKER_ORG: nebari
  GPU_BASE_IMAGE: nvidia/cuda:11.7.0-base-ubuntu20.04
  GPU_IMAGE_SUFFIX: gpu
  BASE_IMAGE: ubuntu:20.04

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  build-images:
    name: "Build Docker Images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - jupyterlab
          - jupyterhub
          - dask-worker
        platform:
          - gpu
          - cpu
        exclude:
          # excludes JupyterHub/GPU
          - dockerfile: jupyterhub
            platform: gpu

    steps:
      - name: "Checkout Repository 🛎️"
        uses: actions/checkout@v3

      - name: "Set up Docker Buildx 🛠️"
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Container Registry 🔐"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Login to Quay Container Registry 🔐"
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
