# Build and push images to:
# GitHub Container Registry (ghcr.io)
# Red Hat Container Registry (quay.io)
name: "Build Docker Images"

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile.*"
      - "*/environment.yaml"
      - ".github/workflows/build-push-docker.yaml"
    tags:
      - "*"
  pull_request:
    paths:
      - "Dockerfile.*"
      - "*/environment.yaml"
      - ".github/workflows/build-push-docker.yaml"

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  build-images:
    name: "Build Docker Images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - jupyterlab
          - jupyterhub
          - dask-worker
    steps:
      - name: "Checkout Repository 🛎️"
        uses: actions/checkout@v3

      - name: "Set up Docker Buildx 🛠️"
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Container Registry 🔐"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: "Login to Quay Container Registry 🔐"
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: "Lint Dockerfiles 🔍"
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: Dockerfile.${{ matrix.dockerfile }}
          output_format: tty
          error_level: 0

      - name: "Generate Docker images tags 🏷️"
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            "quay.io/nebari/nebari-${{ matrix.dockerfile }}"
            "ghcr.io/nebari-dev/nebari-${{ matrix.dockerfile }}"
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: "Inspect image dir tree 🔍"
        run: |
          sudo apt-get install tree
          tree .

      - name: "Set tag var 🏷️"
        id: var
        run: echo ::set-output name=docker_tag::$(echo "${{ steps.meta.outputs.tags }}" | sed -n 1p)

      - name: "Build docker images 🐳"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: "Dockerfile.${{ matrix.dockerfile }}"
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Enable caching for Trivy 🗃️"
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/cache@v2.1.4
        with:
          path: .trivy
          key: ${{ runner.os }}-trivy-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-trivy-

      - name: "Run Trivy vulnerability scanner 🔍"
        if: ${{ github.event_name == 'pull_request' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.var.outputs.docker_tag }}
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          cache-dir: .trivy

      - name: "Upload Trivy scan results to GitHub Security tab 📤"
        if: ${{ github.event_name == 'pull_request' }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"

      - name: "Correct Trivy cache permissions 🧹"
        if: ${{ github.event_name == 'pull_request' }}
        run: sudo chown -R $USER:$GROUP .trivy
