name: Build and Test

on:
  pull_request:
    paths:
      - ".github/workflows/docker-build-test.yaml"

      # We use local reusable workflows to make architecture clean an simple
      # https://docs.github.com/en/actions/using-workflows/reusing-workflows
      - ".github/actions/build-artifact-upload/**"
      - ".github/actions/load-image/**"
      - ".github/actions/create-env-run/**"

      - "dask-worker/**"
      - "jupyterlab/**"
      - "jupyterhub/**"
      - "scripts/**"

  push:
    paths:
      - ".github/workflows/docker-build-test.yaml"

      - ".github/actions/build-artifact-upload/**"
      - ".github/actions/load-image/**"
      - ".github/actions/create-env-run/**"

      - "dask-worker/**"
      - "jupyterlab/**"
      - "jupyterhub/**"
      - "scripts/**"

  workflow_dispatch:


# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  lint-docker-files:
    if: github.event.pull_request.merged == false
    name: 'Build & test Docker Images'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - jupyterlab
          - jupyterhub
          - dask-worker
    steps:
      - name: Checkout Infrastructure ⚡️
        uses: actions/checkout@v3

      - name: Lint docker file
        uses: ./.github/actions/lint-docker-files
        with:
          file-path: ${{ matrix.image }}/Dockerfile.${{ matrix.image }}

  validate-conda-environment:
    if: github.event.pull_request.merged == false
    name: 'Build & test Docker Images'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - jupyterlab
          - jupyterhub
          - dask-worker
    steps:
      - name: Checkout Infrastructure ⚡️
        uses: actions/checkout@v3

      - name: Build environment
        uses: ./.github/actions/build-conda-env
        with:
          environment-path: ${{ matrix.image }}/environment.yaml

  docker-build-test:
    # Avoid running the pipeline twice, if the PR is already merged
    if: github.event.pull_request.merged == false
    name: 'Build & test Docker Images'
    runs-on: ubuntu-latest
    needs: [lint-docker-files, validate-conda-environment]
    strategy:
      matrix:
        image:
          - jupyterlab
          - jupyterhub
          - dask-worker

    steps:
      - name: Checkout Infrastructure ⚡️
        uses: actions/checkout@v3

      - name: Set up Dev environment 📦
        uses: ./.github/actions/create-env-run
        with:
          python-version: 3.8

      # - name: build-amd64
      #   uses: ./.github/actions/build-artifact-upload
      #   with:
      #     dockerFile: Dockerfile.${{ matrix.image }}
      #     image: ${{ matrix.image }}
      #     platform: amd64

      # - name: load-image amd64
      #   uses: ./.github/actions/load-image
      #   with:
      #     image: ${{ matrix.image }}
      #     platform: amd64